# Generated by Django 4.2 on 2023-04-15 14:15

import backend.API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_appuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='city',
            field=models.CharField(default='Rzeszow', max_length=40),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='mobile_phone',
            field=models.CharField(default='000000000', max_length=9, unique=True, validators=[backend.API.models.mobile_address_valid]),
        ),
        migrations.AddField(
            model_name='appuser',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='appuser',
            name='region',
            field=models.CharField(default='Podkarpackie', max_length=60),
        ),
        migrations.AddField(
            model_name='appuser',
            name='surname',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='appuser',
            name='zip_code',
            field=models.CharField(default='00-000', max_length=6, validators=[backend.API.models.zip_code_valid]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
