# Generated by Django 4.2 on 2023-04-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_appuser_mobile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='city',
        ),
    ]
