# Generated by Django 4.2 on 2023-04-15 14:23

import backend.API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_appuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='city',
            field=models.CharField(default='Rzeszow', max_length=40),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=9, validators=[backend.API.models.mobile_address_valid]),
        ),
    ]
