# Generated by Django 4.2 on 2023-04-15 14:25

import backend.API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_appuser_city_alter_appuser_mobile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='region',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='surname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='zip_code',
            field=models.CharField(max_length=6, validators=[backend.API.models.zip_code_valid]),
        ),
    ]
