# Generated by Django 4.2 on 2023-04-15 14:53

import backend.API.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_appuser_city_alter_appuser_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemiTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=40)),
                ('production_year', models.DateField()),
                ('registration_number', models.CharField(max_length=8, unique=True, validators=[backend.API.models.registration_num_validator])),
                ('semi_note', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=40)),
                ('power', models.IntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(999)])),
                ('registration_number', models.CharField(max_length=8, validators=[backend.API.models.registration_num_validator])),
                ('driven_length', models.IntegerField()),
                ('production_date', models.DateField()),
                ('avaiable', models.CharField(choices=[('Wol', 'Wolny'), ('Zaj', 'Zajety'), ('Awar', 'Awaria')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleReceivment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateField(auto_created=True)),
                ('data_ended', models.DateField()),
                ('semi_trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.semitrailer')),
                ('truck', models.ForeignKey(blank=backend.API.models.Truck, on_delete=django.db.models.deletion.CASCADE, to='API.truck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TruckEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest', models.BooleanField(default=True)),
                ('chains', models.BooleanField(default=True)),
                ('jack_hitch', models.BooleanField(default=True)),
                ('planetar_key', models.BooleanField(default=True)),
                ('manometer', models.BooleanField(default=True)),
                ('avaiable', models.CharField(choices=[('Wol', 'Wolny'), ('Zaj', 'Zajety'), ('Awar', 'Awaria')], max_length=4)),
                ('tire_pumping_wire', models.BooleanField(default=True)),
                ('complete_status', models.BooleanField(default=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.truck')),
            ],
        ),
        migrations.CreateModel(
            name='SemiTrailerEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belts', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(12)])),
                ('corners', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(16)])),
                ('aluminium_stick', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(20)])),
                ('wide_stick', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)])),
                ('ladder', models.BooleanField(default=True)),
                ('roof_stick', models.BooleanField(default=True)),
                ('dimenstion_board', models.BooleanField(default=True)),
                ('semi_trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.semitrailer')),
            ],
        ),
    ]
