# Generated by Django 4.2 on 2023-04-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_truck_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclereceivment',
            name='data_ended',
            field=models.DateField(blank=True),
        ),
    ]
