# Generated by Django 4.2 on 2023-04-20 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_vehiclereceivment_complain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclereceivment',
            name='complain',
            field=models.CharField(choices=[('T', 'Tak'), ('N', 'Nie'), ('A', 'Awaria')], default='N', max_length=1),
        ),
        migrations.CreateModel(
            name='TruckComplainPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_photo', models.FileField(upload_to='media')),
                ('receivment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.vehiclereceivment')),
            ],
        ),
        migrations.CreateModel(
            name='SemiTrailerComplainPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semitrailer_photo', models.FileField(upload_to='media')),
                ('receivment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.vehiclereceivment')),
            ],
        ),
    ]
