# Generated by Django 4.2 on 2023-04-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_alter_vehiclereceivment_complain_truckcomplainphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semitrailer',
            name='avaiable',
            field=models.CharField(choices=[('Wol', 'Wolny'), ('Zaj', 'Zajety'), ('Awar', 'Awaria')], default='Wol', max_length=4),
        ),
    ]
