# Generated by Django 4.2 on 2023-04-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_alter_semitrailercomplainphoto_semitrailer_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckequipment',
            name='avaiable',
        ),
    ]
