# Generated by Django 4.2 on 2023-04-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_remove_truckequipment_avaiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckequipment',
            name='receivment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.vehiclereceivment'),
        ),
    ]
