# Generated by Django 4.2 on 2023-04-28 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_semitrailerequipment_receivment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semitrailerequipment',
            name='aluminium_stick',
            field=models.IntegerField(default=12, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='semitrailerequipment',
            name='belts',
            field=models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='semitrailerequipment',
            name='corners',
            field=models.IntegerField(default=8, validators=[django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='semitrailerequipment',
            name='wide_stick',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
