# Generated by Django 4.1.7 on 2023-05-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_appuser_own_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclereceivment',
            name='target_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
