# Generated by Django 4.2 on 2023-05-23 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_vehiclereceivment_target_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semitrailer',
            name='avaiable',
            field=models.CharField(choices=[('Woln', 'Wolny'), ('Zaj', 'Zajety'), ('Awar', 'Awaria')], default='Woln', max_length=4),
        ),
        migrations.AlterField(
            model_name='truck',
            name='avaiable',
            field=models.CharField(choices=[('Woln', 'Wolny'), ('Zaje', 'Zajety'), ('Awar', 'Awaria')], default='Woln', max_length=4),
        ),
        migrations.AlterField(
            model_name='vehiclereceivment',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.truck'),
        ),
    ]
